### ISSUE TITLE
get /cart returns only one result, user should have the ability to query for multiple mixtapes

### ISSUE THREAD

**Issue by heyitsyuliya** [daring-durian/mixtape-4-u#59]
Need to fix the main route in /api/cart.js, this is blocking cart functionality, the component is expecting a list of mixtapes, but receives one object instead
<img width="963" alt="Screen Shot 2021-01-17 at 9 15 38 AM" src="https://user-images.githubusercontent.com/25597423/104845740-0adc7400-58a5-11eb-8732-cfee82e0d1a5.png">

**Comment by kmorawski94** [comment]
This was fixed! Our express route now returns an array of their active mixtapes
